# Part 1
Creating a Formatted CSV.

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('580SurveyCleanup.csv')

In [ ]:
df_1 = data.iloc[:,1:12]

In [ ]:
df_1.columns = df_1.iloc[0]
df_1 = df_1[1:]

In [ ]:
df_1

In [ ]:
# def combineCol(start, end, df3):
#   tempLst = []
#   diff = end - start + 1
#   # return pd.DataFrame(df3.iloc[0:diff])
#   # return pd.DataFrame(df3.iloc[:,])

Function to compile all questions and remove null entries.

In [ ]:
def compileQuestions(start, end):
  temp = [i for i in range(start, end+1)]
  df2 = data.iloc[:,temp]
  df2.columns = df2.iloc[0].astype(str)
  df2 = df2[1:]
  colLst = list(df2.columns)
  # df2[colLst] = df2[colLst].astype(str)
  # print(colLst)
  # df3 = df2.loc[:, colLst].replace(1, pd.Series(df2.columns, df2.columns)).fillna('')
  df3 = df2.loc[:, colLst].replace("1", pd.Series(df2.columns, df2.columns)).fillna('')
  # df4 = combineCol(start, end, df3)
  return df3

In [ ]:
qDict = {
    1 : [12, 13],
    2 : [14, 17],
    3 : [18, 18],
    4 : [19, 19],
    5 : [20, 20],
    6 : [21, 21],
    7 : [22, 22],
    8 : [23, 26],
    9 : [27, 29],
    10 : [30, 34],
    11 : [35, 39],
    12 : [40, 44],
    13 : [45, 45]
}

In [ ]:
dFLst = []
for q in qDict:
  d = compileQuestions(qDict[q][0], qDict[q][1])
  dFLst.append(d)

In [ ]:
colLst = list(dFLst[0].columns)
dFLst[0] = dFLst[0].loc[:, colLst].replace(1, pd.Series(dFLst[0].columns, dFLst[0].columns)).fillna('')

Combining columns together to form one single column per question

In [ ]:
dFLst[0] = pd.DataFrame(dFLst[0].iloc[:,0] + dFLst[0].iloc[:,1])
dFLst[1] = pd.DataFrame(dFLst[1].iloc[:,0] + dFLst[1].iloc[:,1] + dFLst[1].iloc[:,2]+ dFLst[1].iloc[:,3])
dFLst[2] = pd.DataFrame(dFLst[2].iloc[:,0])
dFLst[3] = pd.DataFrame(dFLst[3].iloc[:,0])
dFLst[4] = pd.DataFrame(dFLst[4].iloc[:,0])
dFLst[5] = pd.DataFrame(dFLst[5].iloc[:,0])
dFLst[6] = pd.DataFrame(dFLst[6].iloc[:,0])
dFLst[7] = pd.DataFrame(dFLst[7].iloc[:,0] + dFLst[7].iloc[:,1] + dFLst[7].iloc[:,2] + dFLst[7].iloc[:,3])
dFLst[8] = pd.DataFrame(dFLst[8].iloc[:,0] + dFLst[8].iloc[:,1] + dFLst[8].iloc[:,2])
dFLst[9] = pd.DataFrame(dFLst[9].iloc[:,0] + dFLst[9].iloc[:,1] + dFLst[9].iloc[:,2] + dFLst[9].iloc[:,3] + dFLst[9].iloc[:,4])
dFLst[10] = pd.DataFrame(dFLst[10].iloc[:,0] + dFLst[10].iloc[:,1] + dFLst[10].iloc[:,2] + dFLst[10].iloc[:,3] + dFLst[10].iloc[:,4])
dFLst[11] = pd.DataFrame(dFLst[11].iloc[:,0] + dFLst[11].iloc[:,1] + dFLst[11].iloc[:,2] + dFLst[11].iloc[:,3] + dFLst[11].iloc[:,4])
dFLst[12] = pd.DataFrame(dFLst[12].iloc[:,0])

In [ ]:
qNum = 1
while qNum != 14:
  colHeader = "Q" + str(qNum)
  dFLst[qNum-1].columns = [colHeader]
  qNum += 1

In [ ]:
final_df = pd.DataFrame()
for df in dFLst:
  final_df = pd.concat([final_df,df],axis=1)

In [ ]:
final_df

In [ ]:
final_df = pd.concat([df_1, final_df], axis=1)

In [ ]:
final_df

The final formatted csv contains fixed column headings and combined questions with one column per question

In [ ]:
final_df.to_csv("FormatedCSV.csv")

# Part 2
Filling missing values and Data Cleaning

In [ ]:
data = pd.read_csv('FormatedCSV.csv')

In [ ]:
data

,Unnamed: 0,Time,Status,Duration (Seconds),Access Code,Email Address,IP Address,Country,Region,City / Town / District,...,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13
0,1,10/3/20 5:49 PM,Completed,11646,NaN,NaN,100.36.167.226,United States,Virginia,Fairfax,...,63,Taiwan,economics,2021-12-31,Apple/MacBook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,NaN
1,2,10/3/20 5:49 PM,Completed,113,NaN,NaN,98.169.26.134,United States,Virginia,Fairfax,...,59,India,Finance,2021-05-01,Apple/MacBook,"Working, but not Full Time",Average user,Average user,Little/none,NaN
2,3,10/3/20 5:49 PM,Completed,572,NaN,NaN,98.169.52.23,United States,Virginia,Greenway Downs,...,70,India,Computer Applications,2022-06-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,4,10/3/20 5:50 PM,Completed,365,NaN,NaN,69.255.182.253,United States,Virginia,Gainesville,...,66,South Korea,Business Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,NaN
4,5,10/3/20 5:51 PM,Completed,92,NaN,NaN,138.88.108.230,United States,NaN,NaN,...,70,US,Yes,2021-01-01,2,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,6,10/3/20 5:59 PM,Incomplete,221,NaN,NaN,108.56.134.80,United States,Virginia,Reston,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,10/3/20 6:23 PM,Completed,115983,NaN,NaN,108.48.175.220,United States,Virginia,Arlington,...,70,pakistan,Finance,2022-07-15,Microsoft/Windows,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,8,10/3/20 7:10 PM,Incomplete,40,NaN,NaN,173.67.199.85,United States,Virginia,Ashburn,...,5.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,10/3/20 7:25 PM,Completed,137,NaN,NaN,74.96.114.12,United States,Virginia,Woodbridge,...,71,china,Economic,2021-12-15,Microsoft/Windows,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,NaN
9,10,10/3/20 7:56 PM,Incomplete,179,NaN,NaN,107.77.241.32,United States,Texas,NaN,...,71,Uzbekistan,Economics with Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,10/3/20 8:14 PM,Completed,127,NaN,NaN,138.88.182.245,United States,Maryland,Takoma Park,...,66,USA,BIT,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,12,10/3/20 9:38 PM,Completed,269,NaN,NaN,72.83.246.60,United States,Virginia,Fairfax,...,66,India,Computer Engineering,2021-05-31,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,13,10/3/20 9:41 PM,Completed,117,NaN,NaN,96.241.43.105,United States,Virginia,Chantilly,...,69,Romania,Biology,2021-08-26,Apple/MacBook,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,14,10/3/20 10:49 PM,Completed,5966,NaN,NaN,71.191.72.223,United States,Virginia,Burke,...,66,India,Cse,2021-12-25,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,NaN
14,15,10/3/20 11:25 PM,Completed,254,NaN,NaN,73.134.53.227,United States,Maryland,Hyattsville,...,67,China,Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,16,10/4/20 12:28 AM,Completed,526,NaN,NaN,73.86.219.52,United States,Maryland,Baltimore,...,72,Uzbekistan,Economics with Finance,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,17,10/4/20 5:22 AM,Completed,398,NaN,NaN,69.138.215.127,United States,Virginia,Arlington,...,68,USA,Economics,2022-05-31,Microsoft/WindowsApple/MacBook,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,18,10/4/20 5:36 AM,Completed,128253,NaN,NaN,72.196.231.70,United States,Virginia,Springfield,...,60,India,Engineering,2021-01-12,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,19,10/4/20 5:47 AM,Completed,239,NaN,NaN,100.15.54.17,United States,Virginia,Woodbridge,...,67,Ethiopia,Accounting and ISOM,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,20,10/4/20 10:32 AM,Completed,255,NaN,NaN,184.170.83.239,United States,Virginia,Rustburg,...,67,United States,Statistics,2021-12-20,Apple/MacBook,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,21,10/4/20 11:03 AM,Completed,256,NaN,NaN,100.36.243.102,United States,Virginia,Fairfax,...,74,United States,Computer Science,2022-05-01,Microsoft/Windows,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,22,10/4/20 12:34 PM,Completed,674,NaN,NaN,108.56.134.80,United States,Virginia,Reston,...,65,India,Computer science,2022-04-16,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,23,10/4/20 1:36 PM,Completed,130,NaN,NaN,73.163.163.82,United States,Maryland,Baltimore,...,67,USA,Mathematics & Statistics,2021-12-18,Microsoft/WindowsApple/MacBook,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,24,10/4/20 1:50 PM,Completed,275,NaN,NaN,138.88.223.87,United States,NaN,NaN,...,75,Nigeria,Economics,2021-05-14,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,25,10/4/20 9:28 PM,Completed,325,NaN,NaN,100.36.50.114,United States,NaN,NaN,...,67,USA,Systems Engineering,2022-12-19,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,26,10/5/20 9:37 AM,Completed,257,NaN,NaN,108.51.59.195,United States,Virginia,Burke,...,68,Taiwan,Civil engineering,2021-05-30,0,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,27,10/5/20 9:36 AM,Completed,657,NaN,NaN,72.83.246.219,United States,Virginia,Fairfax,...,72,India,ECE,2021-12-11,Apple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,28,10/5/20 10:36 AM,Completed,1750,NaN,NaN,100.36.118.186,United States,Virginia,Burke,...,6l,Nigeria,Quantity Surveying,2023-05-24,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,29,10/5/20 11:02 AM,Completed,887,NaN,NaN,172.58.187.98,United States,Maryland,Baltimore,...,64,India,Bachelor of Engineering,2021-12-30,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,30,10/5/20 11:17 AM,Completed,180,NaN,NaN,72.196.230.201,United States,Virginia,Springfield,...,71,India,B.Tech in CS,2021-12-15,Apple/MacBook,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,31,10/5/20 12:52 PM,Completed,392,NaN,NaN,108.18.111.204,United States,Virginia,Lorton,...,56,United States,BS accounting,2021-05-01,Microsoft/Windows,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,32,10/5/20 12:56 PM,Incomplete,192,NaN,NaN,71.191.72.223,United States,Virginia,Burke,...,70,India,Bachelor of engineering,2021-12-21,Microsoft/WindowsApple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,NaN
32,33,10/5/20 1:52 PM,Completed,277,NaN,NaN,184.191.72.8,United States,Virginia,Falls Church,...,7O,United States ; Pakistan,Criminology Law and Soci,2021-12-18,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,34,10/5/20 3:34 PM,Completed,119,NaN,NaN,141.156.160.243,United States,NaN,NaN,...,73,USA,Economics,2022-05-15,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,35,10/5/20 3:41 PM,Completed,149,NaN,NaN,71.206.51.121,United States,Maryland,Frederick,...,68,Vietnam,Finance,2022-12-12,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,36,10/5/20 5:58 PM,Completed,285,NaN,NaN,129.174.252.234,United States,Virginia,Fairfax,...,66,Uzbekistan,Psychology,2021-12-20,OtherAcer/Windows,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

In [ ]:
missing_columns = data.columns[data.isna().any()].tolist()

Columns containing missing values

In [ ]:
missing_columns

['Access Code',
 'Email Address',
 'Region',
 'City / Town / District',
 'Q4',
 'Q5',
 'Q6',
 'Q7',
 'Q8',
 'Q9',
 'Q10',
 'Q11',
 'Q12',
 'Q13']

Since Access Code and Email Address are completely empty, they have been dropped. It won't be possible to populate these columns using some heuristic

In [ ]:
df_1 = data.drop(["Access Code", "Email Address"], axis=1)

In [ ]:
df_1

,Unnamed: 0,Time,Status,Duration (Seconds),IP Address,Country,Region,City / Town / District,Latitude,Longitude,...,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13
0,1,10/3/20 5:49 PM,Completed,11646,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209,...,63,Taiwan,economics,2021-12-31,Apple/MacBook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,NaN
1,2,10/3/20 5:49 PM,Completed,113,98.169.26.134,United States,Virginia,Fairfax,-77.2630,38.8605,...,59,India,Finance,2021-05-01,Apple/MacBook,"Working, but not Full Time",Average user,Average user,Little/none,NaN
2,3,10/3/20 5:49 PM,Completed,572,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645,...,70,India,Computer Applications,2022-06-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,4,10/3/20 5:50 PM,Completed,365,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175,...,66,South Korea,Business Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,NaN
4,5,10/3/20 5:51 PM,Completed,92,138.88.108.230,United States,NaN,NaN,-97.8220,37.7510,...,70,US,Yes,2021-01-01,2,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,6,10/3/20 5:59 PM,Incomplete,221,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,10/3/20 6:23 PM,Completed,115983,108.48.175.220,United States,Virginia,Arlington,-77.0987,38.8600,...,70,pakistan,Finance,2022-07-15,Microsoft/Windows,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,8,10/3/20 7:10 PM,Incomplete,40,173.67.199.85,United States,Virginia,Ashburn,-77.5390,39.0180,...,5.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,10/3/20 7:25 PM,Completed,137,74.96.114.12,United States,Virginia,Woodbridge,-77.3197,38.6780,...,71,china,Economic,2021-12-15,Microsoft/Windows,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,NaN
9,10,10/3/20 7:56 PM,Incomplete,179,107.77.241.32,United States,Texas,NaN,-96.8217,32.7787,...,71,Uzbekistan,Economics with Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,10/3/20 8:14 PM,Completed,127,138.88.182.245,United States,Maryland,Takoma Park,-77.0040,38.9827,...,66,USA,BIT,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,12,10/3/20 9:38 PM,Completed,269,72.83.246.60,United States,Virginia,Fairfax,-77.2630,38.8605,...,66,India,Computer Engineering,2021-05-31,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,13,10/3/20 9:41 PM,Completed,117,96.241.43.105,United States,Virginia,Chantilly,-77.4512,38.9036,...,69,Romania,Biology,2021-08-26,Apple/MacBook,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,14,10/3/20 10:49 PM,Completed,5966,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,66,India,Cse,2021-12-25,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,NaN
14,15,10/3/20 11:25 PM,Completed,254,73.134.53.227,United States,Maryland,Hyattsville,-76.8696,38.9544,...,67,China,Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,16,10/4/20 12:28 AM,Completed,526,73.86.219.52,United States,Maryland,Baltimore,-76.6355,39.3555,...,72,Uzbekistan,Economics with Finance,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,17,10/4/20 5:22 AM,Completed,398,69.138.215.127,United States,Virginia,Arlington,-77.1130,38.8747,...,68,USA,Economics,2022-05-31,Microsoft/WindowsApple/MacBook,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,18,10/4/20 5:36 AM,Completed,128253,72.196.231.70,United States,Virginia,Springfield,-77.2333,38.7438,...,60,India,Engineering,2021-01-12,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,19,10/4/20 5:47 AM,Completed,239,100.15.54.17,United States,Virginia,Woodbridge,-77.3197,38.6780,...,67,Ethiopia,Accounting and ISOM,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,20,10/4/20 10:32 AM,Completed,255,184.170.83.239,United States,Virginia,Rustburg,-79.0985,37.2544,...,67,United States,Statistics,2021-12-20,Apple/MacBook,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,21,10/4/20 11:03 AM,Completed,256,100.36.243.102,United States,Virginia,Fairfax,-77.3375,38.8357,...,74,United States,Computer Science,2022-05-01,Microsoft/Windows,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,22,10/4/20 12:34 PM,Completed,674,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,65,India,Computer science,2022-04-16,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,23,10/4/20 1:36 PM,Completed,130,73.163.163.82,United States,Maryland,Baltimore,-76.5570,39.2784,...,67,USA,Mathematics & Statistics,2021-12-18,Microsoft/WindowsApple/MacBook,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,24,10/4/20 1:50 PM,Completed,275,138.88.223.87,United States,NaN,NaN,-97.8220,37.7510,...,75,Nigeria,Economics,2021-05-14,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,25,10/4/20 9:28 PM,Completed,325,100.36.50.114,United States,NaN,NaN,-97.8220,37.7510,...,67,USA,Systems Engineering,2022-12-19,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,26,10/5/20 9:37 AM,Completed,257,108.51.59.195,United States,Virginia,Burke,-77.2866,38.7851,...,68,Taiwan,Civil engineering,2021-05-30,0,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,27,10/5/20 9:36 AM,Completed,657,72.83.246.219,United States,Virginia,Fairfax,-77.2630,38.8605,...,72,India,ECE,2021-12-11,Apple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,28,10/5/20 10:36 AM,Completed,1750,100.36.118.186,United States,Virginia,Burke,-77.2866,38.7851,...,6l,Nigeria,Quantity Surveying,2023-05-24,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,29,10/5/20 11:02 AM,Completed,887,172.58.187.98,United States,Maryland,Baltimore,-76.6949,39.2820,...,64,India,Bachelor of Engineering,2021-12-30,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,30,10/5/20 11:17 AM,Completed,180,72.196.230.201,United States,Virginia,Springfield,-77.2333,38.7438,...,71,India,B.Tech in CS,2021-12-15,Apple/MacBook,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,31,10/5/20 12:52 PM,Completed,392,108.18.111.204,United States,Virginia,Lorton,-77.2060,38.6911,...,56,United States,BS accounting,2021-05-01,Microsoft/Windows,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,32,10/5/20 12:56 PM,Incomplete,192,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,70,India,Bachelor of engineering,2021-12-21,Microsoft/WindowsApple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,NaN
32,33,10/5/20 1:52 PM,Completed,277,184.191.72.8,United States,Virginia,Falls Church,-77.1425,38.8472,...,7O,United States ; Pakistan,Criminology Law and Soci,2021-12-18,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,34,10/5/20 3:34 PM,Completed,119,141.156.160.243,United States,NaN,NaN,-97.8220,37.7510,...,73,USA,Economics,2022-05-15,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,35,10/5/20 3:41 PM,Completed,149,71.206.51.121,United States,Maryland,Frederick,-77.2758,39.4624,...,68,Vietnam,Finance,2022-12-12,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,36,10/5/20 5:58 PM,Completed,285,129.174.252.234,United States,Virginia,Fairfax,-77.3375,38.8357,...,66,Uzbekistan,Psychology,2021-12-20,OtherAcer/Windows,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

Replacing empty values of Region with the mode, or the most repeated values of the column since it has more chances of being repeated.

In [ ]:
df_1['Region'].value_counts()

Virginia    25
Maryland     6
Texas        1
Name: Region, dtype: int64

In [ ]:
modeRegion = df_1["Region"].mode()

In [ ]:
df_1["Region"].fillna(modeRegion.values[0], inplace = True)

In [ ]:
df_1

,Unnamed: 0,Time,Status,Duration (Seconds),IP Address,Country,Region,City / Town / District,Latitude,Longitude,...,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13
0,1,10/3/20 5:49 PM,Completed,11646,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209,...,63,Taiwan,economics,2021-12-31,Apple/MacBook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,NaN
1,2,10/3/20 5:49 PM,Completed,113,98.169.26.134,United States,Virginia,Fairfax,-77.2630,38.8605,...,59,India,Finance,2021-05-01,Apple/MacBook,"Working, but not Full Time",Average user,Average user,Little/none,NaN
2,3,10/3/20 5:49 PM,Completed,572,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645,...,70,India,Computer Applications,2022-06-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,4,10/3/20 5:50 PM,Completed,365,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175,...,66,South Korea,Business Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,NaN
4,5,10/3/20 5:51 PM,Completed,92,138.88.108.230,United States,Virginia,NaN,-97.8220,37.7510,...,70,US,Yes,2021-01-01,2,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,6,10/3/20 5:59 PM,Incomplete,221,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,10/3/20 6:23 PM,Completed,115983,108.48.175.220,United States,Virginia,Arlington,-77.0987,38.8600,...,70,pakistan,Finance,2022-07-15,Microsoft/Windows,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,8,10/3/20 7:10 PM,Incomplete,40,173.67.199.85,United States,Virginia,Ashburn,-77.5390,39.0180,...,5.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,10/3/20 7:25 PM,Completed,137,74.96.114.12,United States,Virginia,Woodbridge,-77.3197,38.6780,...,71,china,Economic,2021-12-15,Microsoft/Windows,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,NaN
9,10,10/3/20 7:56 PM,Incomplete,179,107.77.241.32,United States,Texas,NaN,-96.8217,32.7787,...,71,Uzbekistan,Economics with Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,10/3/20 8:14 PM,Completed,127,138.88.182.245,United States,Maryland,Takoma Park,-77.0040,38.9827,...,66,USA,BIT,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,12,10/3/20 9:38 PM,Completed,269,72.83.246.60,United States,Virginia,Fairfax,-77.2630,38.8605,...,66,India,Computer Engineering,2021-05-31,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,13,10/3/20 9:41 PM,Completed,117,96.241.43.105,United States,Virginia,Chantilly,-77.4512,38.9036,...,69,Romania,Biology,2021-08-26,Apple/MacBook,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,14,10/3/20 10:49 PM,Completed,5966,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,66,India,Cse,2021-12-25,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,NaN
14,15,10/3/20 11:25 PM,Completed,254,73.134.53.227,United States,Maryland,Hyattsville,-76.8696,38.9544,...,67,China,Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,16,10/4/20 12:28 AM,Completed,526,73.86.219.52,United States,Maryland,Baltimore,-76.6355,39.3555,...,72,Uzbekistan,Economics with Finance,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,17,10/4/20 5:22 AM,Completed,398,69.138.215.127,United States,Virginia,Arlington,-77.1130,38.8747,...,68,USA,Economics,2022-05-31,Microsoft/WindowsApple/MacBook,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,18,10/4/20 5:36 AM,Completed,128253,72.196.231.70,United States,Virginia,Springfield,-77.2333,38.7438,...,60,India,Engineering,2021-01-12,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,19,10/4/20 5:47 AM,Completed,239,100.15.54.17,United States,Virginia,Woodbridge,-77.3197,38.6780,...,67,Ethiopia,Accounting and ISOM,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,20,10/4/20 10:32 AM,Completed,255,184.170.83.239,United States,Virginia,Rustburg,-79.0985,37.2544,...,67,United States,Statistics,2021-12-20,Apple/MacBook,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,21,10/4/20 11:03 AM,Completed,256,100.36.243.102,United States,Virginia,Fairfax,-77.3375,38.8357,...,74,United States,Computer Science,2022-05-01,Microsoft/Windows,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,22,10/4/20 12:34 PM,Completed,674,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,65,India,Computer science,2022-04-16,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,23,10/4/20 1:36 PM,Completed,130,73.163.163.82,United States,Maryland,Baltimore,-76.5570,39.2784,...,67,USA,Mathematics & Statistics,2021-12-18,Microsoft/WindowsApple/MacBook,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,24,10/4/20 1:50 PM,Completed,275,138.88.223.87,United States,Virginia,NaN,-97.8220,37.7510,...,75,Nigeria,Economics,2021-05-14,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,25,10/4/20 9:28 PM,Completed,325,100.36.50.114,United States,Virginia,NaN,-97.8220,37.7510,...,67,USA,Systems Engineering,2022-12-19,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,26,10/5/20 9:37 AM,Completed,257,108.51.59.195,United States,Virginia,Burke,-77.2866,38.7851,...,68,Taiwan,Civil engineering,2021-05-30,0,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,27,10/5/20 9:36 AM,Completed,657,72.83.246.219,United States,Virginia,Fairfax,-77.2630,38.8605,...,72,India,ECE,2021-12-11,Apple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,28,10/5/20 10:36 AM,Completed,1750,100.36.118.186,United States,Virginia,Burke,-77.2866,38.7851,...,6l,Nigeria,Quantity Surveying,2023-05-24,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,29,10/5/20 11:02 AM,Completed,887,172.58.187.98,United States,Maryland,Baltimore,-76.6949,39.2820,...,64,India,Bachelor of Engineering,2021-12-30,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,30,10/5/20 11:17 AM,Completed,180,72.196.230.201,United States,Virginia,Springfield,-77.2333,38.7438,...,71,India,B.Tech in CS,2021-12-15,Apple/MacBook,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,31,10/5/20 12:52 PM,Completed,392,108.18.111.204,United States,Virginia,Lorton,-77.2060,38.6911,...,56,United States,BS accounting,2021-05-01,Microsoft/Windows,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,32,10/5/20 12:56 PM,Incomplete,192,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,70,India,Bachelor of engineering,2021-12-21,Microsoft/WindowsApple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,NaN
32,33,10/5/20 1:52 PM,Completed,277,184.191.72.8,United States,Virginia,Falls Church,-77.1425,38.8472,...,7O,United States ; Pakistan,Criminology Law and Soci,2021-12-18,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,34,10/5/20 3:34 PM,Completed,119,141.156.160.243,United States,Virginia,NaN,-97.8220,37.7510,...,73,USA,Economics,2022-05-15,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,35,10/5/20 3:41 PM,Completed,149,71.206.51.121,United States,Maryland,Frederick,-77.2758,39.4624,...,68,Vietnam,Finance,2022-12-12,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,36,10/5/20 5:58 PM,Completed,285,129.174.252.234,United States,Virginia,Fairfax,-77.3375,38.8357,...,66,Uzbekistan,Psychology,2021-12-20,OtherAcer/Windows,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

In [ ]:
missing_columns_2 = df_1.columns[df_1.isna().any()].tolist()

In [ ]:
missing_columns_2

['City / Town / District',
 'Q4',
 'Q5',
 'Q6',
 'Q7',
 'Q8',
 'Q9',
 'Q10',
 'Q11',
 'Q12',
 'Q13']

In [ ]:
df_1['City / Town / District'].value_counts()

Fairfax           6
Burke             4
Baltimore         3
Reston            2
Arlington         2
Woodbridge        2
Springfield       2
Falls Church      1
Lorton            1
Rustburg          1
Chantilly         1
Hyattsville       1
Greenway Downs    1
Takoma Park       1
Ashburn           1
Gainesville       1
Frederick         1
Name: City / Town / District, dtype: int64

Fixing and cleaning Age values

In [ ]:
import numpy as np

In [ ]:
df_2 = df_1
df_2['Q3'] = df_2['Q3'].str.replace(' ', '')

In [ ]:
df_2["Q3"] = df_2['Q3'].astype(int)

In [ ]:
df_2['Q3'] = np.where(df_2['Q3'] > 100, 2022 - df_2['Q3'], df_2['Q3'])

In [ ]:
df_2

,Unnamed: 0,Time,Status,Duration (Seconds),IP Address,Country,Region,City / Town / District,Latitude,Longitude,...,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13
0,1,10/3/20 5:49 PM,Completed,11646,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209,...,63,Taiwan,economics,2021-12-31,Apple/MacBook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,NaN
1,2,10/3/20 5:49 PM,Completed,113,98.169.26.134,United States,Virginia,Fairfax,-77.2630,38.8605,...,59,India,Finance,2021-05-01,Apple/MacBook,"Working, but not Full Time",Average user,Average user,Little/none,NaN
2,3,10/3/20 5:49 PM,Completed,572,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645,...,70,India,Computer Applications,2022-06-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,4,10/3/20 5:50 PM,Completed,365,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175,...,66,South Korea,Business Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,NaN
4,5,10/3/20 5:51 PM,Completed,92,138.88.108.230,United States,Virginia,NaN,-97.8220,37.7510,...,70,US,Yes,2021-01-01,2,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,6,10/3/20 5:59 PM,Incomplete,221,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,10/3/20 6:23 PM,Completed,115983,108.48.175.220,United States,Virginia,Arlington,-77.0987,38.8600,...,70,pakistan,Finance,2022-07-15,Microsoft/Windows,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,8,10/3/20 7:10 PM,Incomplete,40,173.67.199.85,United States,Virginia,Ashburn,-77.5390,39.0180,...,5.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,10/3/20 7:25 PM,Completed,137,74.96.114.12,United States,Virginia,Woodbridge,-77.3197,38.6780,...,71,china,Economic,2021-12-15,Microsoft/Windows,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,NaN
9,10,10/3/20 7:56 PM,Incomplete,179,107.77.241.32,United States,Texas,NaN,-96.8217,32.7787,...,71,Uzbekistan,Economics with Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,10/3/20 8:14 PM,Completed,127,138.88.182.245,United States,Maryland,Takoma Park,-77.0040,38.9827,...,66,USA,BIT,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,12,10/3/20 9:38 PM,Completed,269,72.83.246.60,United States,Virginia,Fairfax,-77.2630,38.8605,...,66,India,Computer Engineering,2021-05-31,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,13,10/3/20 9:41 PM,Completed,117,96.241.43.105,United States,Virginia,Chantilly,-77.4512,38.9036,...,69,Romania,Biology,2021-08-26,Apple/MacBook,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,14,10/3/20 10:49 PM,Completed,5966,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,66,India,Cse,2021-12-25,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,NaN
14,15,10/3/20 11:25 PM,Completed,254,73.134.53.227,United States,Maryland,Hyattsville,-76.8696,38.9544,...,67,China,Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,16,10/4/20 12:28 AM,Completed,526,73.86.219.52,United States,Maryland,Baltimore,-76.6355,39.3555,...,72,Uzbekistan,Economics with Finance,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,17,10/4/20 5:22 AM,Completed,398,69.138.215.127,United States,Virginia,Arlington,-77.1130,38.8747,...,68,USA,Economics,2022-05-31,Microsoft/WindowsApple/MacBook,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,18,10/4/20 5:36 AM,Completed,128253,72.196.231.70,United States,Virginia,Springfield,-77.2333,38.7438,...,60,India,Engineering,2021-01-12,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,19,10/4/20 5:47 AM,Completed,239,100.15.54.17,United States,Virginia,Woodbridge,-77.3197,38.6780,...,67,Ethiopia,Accounting and ISOM,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,20,10/4/20 10:32 AM,Completed,255,184.170.83.239,United States,Virginia,Rustburg,-79.0985,37.2544,...,67,United States,Statistics,2021-12-20,Apple/MacBook,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,21,10/4/20 11:03 AM,Completed,256,100.36.243.102,United States,Virginia,Fairfax,-77.3375,38.8357,...,74,United States,Computer Science,2022-05-01,Microsoft/Windows,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,22,10/4/20 12:34 PM,Completed,674,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,65,India,Computer science,2022-04-16,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,23,10/4/20 1:36 PM,Completed,130,73.163.163.82,United States,Maryland,Baltimore,-76.5570,39.2784,...,67,USA,Mathematics & Statistics,2021-12-18,Microsoft/WindowsApple/MacBook,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,24,10/4/20 1:50 PM,Completed,275,138.88.223.87,United States,Virginia,NaN,-97.8220,37.7510,...,75,Nigeria,Economics,2021-05-14,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,25,10/4/20 9:28 PM,Completed,325,100.36.50.114,United States,Virginia,NaN,-97.8220,37.7510,...,67,USA,Systems Engineering,2022-12-19,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,26,10/5/20 9:37 AM,Completed,257,108.51.59.195,United States,Virginia,Burke,-77.2866,38.7851,...,68,Taiwan,Civil engineering,2021-05-30,0,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,27,10/5/20 9:36 AM,Completed,657,72.83.246.219,United States,Virginia,Fairfax,-77.2630,38.8605,...,72,India,ECE,2021-12-11,Apple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,28,10/5/20 10:36 AM,Completed,1750,100.36.118.186,United States,Virginia,Burke,-77.2866,38.7851,...,6l,Nigeria,Quantity Surveying,2023-05-24,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,29,10/5/20 11:02 AM,Completed,887,172.58.187.98,United States,Maryland,Baltimore,-76.6949,39.2820,...,64,India,Bachelor of Engineering,2021-12-30,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,30,10/5/20 11:17 AM,Completed,180,72.196.230.201,United States,Virginia,Springfield,-77.2333,38.7438,...,71,India,B.Tech in CS,2021-12-15,Apple/MacBook,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,31,10/5/20 12:52 PM,Completed,392,108.18.111.204,United States,Virginia,Lorton,-77.2060,38.6911,...,56,United States,BS accounting,2021-05-01,Microsoft/Windows,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,32,10/5/20 12:56 PM,Incomplete,192,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,70,India,Bachelor of engineering,2021-12-21,Microsoft/WindowsApple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,NaN
32,33,10/5/20 1:52 PM,Completed,277,184.191.72.8,United States,Virginia,Falls Church,-77.1425,38.8472,...,7O,United States ; Pakistan,Criminology Law and Soci,2021-12-18,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,34,10/5/20 3:34 PM,Completed,119,141.156.160.243,United States,Virginia,NaN,-97.8220,37.7510,...,73,USA,Economics,2022-05-15,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,35,10/5/20 3:41 PM,Completed,149,71.206.51.121,United States,Maryland,Frederick,-77.2758,39.4624,...,68,Vietnam,Finance,2022-12-12,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,36,10/5/20 5:58 PM,Completed,285,129.174.252.234,United States,Virginia,Fairfax,-77.3375,38.8357,...,66,Uzbekistan,Psychology,2021-12-20,OtherAcer/Windows,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

Fixing and Cleaning Height values
Removed string values, filled empty values with the mean of heights since it is a quantitative quality.

In [ ]:
df_3 = df_1
df_3['Q4'] = np.where(df_3['Q4'] == "7O", "70", df_3['Q4'])
df_3['Q4'] = np.where(df_3['Q4'] == "6l", "61", df_3['Q4'])

In [ ]:
df_3['Q4'] = df_3['Q4'].astype(float)

In [ ]:
df_3['Q4'] = np.where(df_3['Q4'] < 10, df_3['Q4'] * 12, df_3['Q4'])

In [ ]:
df_3['Q4']

0     63.0
1     59.0
2     70.0
3     66.0
4     70.0
5      NaN
6     70.0
7     62.4
8     71.0
9     71.0
10    66.0
11    66.0
12    69.0
13    66.0
14    67.0
15    72.0
16    68.0
17    60.0
18    67.0
19    67.0
20    74.0
21    65.0
22    67.0
23    75.0
24    67.0
25    68.0
26    72.0
27    61.0
28    64.0
29    71.0
30    56.0
31    70.0
32    70.0
33    73.0
34    68.0
35    66.0
Name: Q4, dtype: float64

In [ ]:
df_3['Q4'].fillna(df_3['Q4'].mean(), inplace=True)

In [ ]:
df_3['Q4']

0     63.000000
1     59.000000
2     70.000000
3     66.000000
4     70.000000
5     67.354286
6     70.000000
7     62.400000
8     71.000000
9     71.000000
10    66.000000
11    66.000000
12    69.000000
13    66.000000
14    67.000000
15    72.000000
16    68.000000
17    60.000000
18    67.000000
19    67.000000
20    74.000000
21    65.000000
22    67.000000
23    75.000000
24    67.000000
25    68.000000
26    72.000000
27    61.000000
28    64.000000
29    71.000000
30    56.000000
31    70.000000
32    70.000000
33    73.000000
34    68.000000
35    66.000000
Name: Q4, dtype: float64

In [ ]:
df_3['Q4'] = df_3['Q4'].astype(int)

In [ ]:
df_3['Q4']

0     63
1     59
2     70
3     66
4     70
5     67
6     70
7     62
8     71
9     71
10    66
11    66
12    69
13    66
14    67
15    72
16    68
17    60
18    67
19    67
20    74
21    65
22    67
23    75
24    67
25    68
26    72
27    61
28    64
29    71
30    56
31    70
32    70
33    73
34    68
35    66
Name: Q4, dtype: int64

In [ ]:
df_3

,Unnamed: 0,Time,Status,Duration (Seconds),IP Address,Country,Region,City / Town / District,Latitude,Longitude,...,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13
0,1,10/3/20 5:49 PM,Completed,11646,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209,...,63,Taiwan,economics,2021-12-31,Apple/MacBook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,NaN
1,2,10/3/20 5:49 PM,Completed,113,98.169.26.134,United States,Virginia,Fairfax,-77.2630,38.8605,...,59,India,Finance,2021-05-01,Apple/MacBook,"Working, but not Full Time",Average user,Average user,Little/none,NaN
2,3,10/3/20 5:49 PM,Completed,572,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645,...,70,India,Computer Applications,2022-06-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,4,10/3/20 5:50 PM,Completed,365,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175,...,66,South Korea,Business Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,NaN
4,5,10/3/20 5:51 PM,Completed,92,138.88.108.230,United States,Virginia,NaN,-97.8220,37.7510,...,70,US,Yes,2021-01-01,2,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,6,10/3/20 5:59 PM,Incomplete,221,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,10/3/20 6:23 PM,Completed,115983,108.48.175.220,United States,Virginia,Arlington,-77.0987,38.8600,...,70,pakistan,Finance,2022-07-15,Microsoft/Windows,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,8,10/3/20 7:10 PM,Incomplete,40,173.67.199.85,United States,Virginia,Ashburn,-77.5390,39.0180,...,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,10/3/20 7:25 PM,Completed,137,74.96.114.12,United States,Virginia,Woodbridge,-77.3197,38.6780,...,71,china,Economic,2021-12-15,Microsoft/Windows,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,NaN
9,10,10/3/20 7:56 PM,Incomplete,179,107.77.241.32,United States,Texas,NaN,-96.8217,32.7787,...,71,Uzbekistan,Economics with Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,10/3/20 8:14 PM,Completed,127,138.88.182.245,United States,Maryland,Takoma Park,-77.0040,38.9827,...,66,USA,BIT,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,12,10/3/20 9:38 PM,Completed,269,72.83.246.60,United States,Virginia,Fairfax,-77.2630,38.8605,...,66,India,Computer Engineering,2021-05-31,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,13,10/3/20 9:41 PM,Completed,117,96.241.43.105,United States,Virginia,Chantilly,-77.4512,38.9036,...,69,Romania,Biology,2021-08-26,Apple/MacBook,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,14,10/3/20 10:49 PM,Completed,5966,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,66,India,Cse,2021-12-25,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,NaN
14,15,10/3/20 11:25 PM,Completed,254,73.134.53.227,United States,Maryland,Hyattsville,-76.8696,38.9544,...,67,China,Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,16,10/4/20 12:28 AM,Completed,526,73.86.219.52,United States,Maryland,Baltimore,-76.6355,39.3555,...,72,Uzbekistan,Economics with Finance,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,17,10/4/20 5:22 AM,Completed,398,69.138.215.127,United States,Virginia,Arlington,-77.1130,38.8747,...,68,USA,Economics,2022-05-31,Microsoft/WindowsApple/MacBook,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,18,10/4/20 5:36 AM,Completed,128253,72.196.231.70,United States,Virginia,Springfield,-77.2333,38.7438,...,60,India,Engineering,2021-01-12,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,19,10/4/20 5:47 AM,Completed,239,100.15.54.17,United States,Virginia,Woodbridge,-77.3197,38.6780,...,67,Ethiopia,Accounting and ISOM,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,20,10/4/20 10:32 AM,Completed,255,184.170.83.239,United States,Virginia,Rustburg,-79.0985,37.2544,...,67,United States,Statistics,2021-12-20,Apple/MacBook,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,21,10/4/20 11:03 AM,Completed,256,100.36.243.102,United States,Virginia,Fairfax,-77.3375,38.8357,...,74,United States,Computer Science,2022-05-01,Microsoft/Windows,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,22,10/4/20 12:34 PM,Completed,674,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,65,India,Computer science,2022-04-16,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,23,10/4/20 1:36 PM,Completed,130,73.163.163.82,United States,Maryland,Baltimore,-76.5570,39.2784,...,67,USA,Mathematics & Statistics,2021-12-18,Microsoft/WindowsApple/MacBook,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,24,10/4/20 1:50 PM,Completed,275,138.88.223.87,United States,Virginia,NaN,-97.8220,37.7510,...,75,Nigeria,Economics,2021-05-14,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,25,10/4/20 9:28 PM,Completed,325,100.36.50.114,United States,Virginia,NaN,-97.8220,37.7510,...,67,USA,Systems Engineering,2022-12-19,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,26,10/5/20 9:37 AM,Completed,257,108.51.59.195,United States,Virginia,Burke,-77.2866,38.7851,...,68,Taiwan,Civil engineering,2021-05-30,0,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,27,10/5/20 9:36 AM,Completed,657,72.83.246.219,United States,Virginia,Fairfax,-77.2630,38.8605,...,72,India,ECE,2021-12-11,Apple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,28,10/5/20 10:36 AM,Completed,1750,100.36.118.186,United States,Virginia,Burke,-77.2866,38.7851,...,61,Nigeria,Quantity Surveying,2023-05-24,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,29,10/5/20 11:02 AM,Completed,887,172.58.187.98,United States,Maryland,Baltimore,-76.6949,39.2820,...,64,India,Bachelor of Engineering,2021-12-30,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,30,10/5/20 11:17 AM,Completed,180,72.196.230.201,United States,Virginia,Springfield,-77.2333,38.7438,...,71,India,B.Tech in CS,2021-12-15,Apple/MacBook,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,31,10/5/20 12:52 PM,Completed,392,108.18.111.204,United States,Virginia,Lorton,-77.2060,38.6911,...,56,United States,BS accounting,2021-05-01,Microsoft/Windows,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,32,10/5/20 12:56 PM,Incomplete,192,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,70,India,Bachelor of engineering,2021-12-21,Microsoft/WindowsApple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,NaN
32,33,10/5/20 1:52 PM,Completed,277,184.191.72.8,United States,Virginia,Falls Church,-77.1425,38.8472,...,70,United States ; Pakistan,Criminology Law and Soci,2021-12-18,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,34,10/5/20 3:34 PM,Completed,119,141.156.160.243,United States,Virginia,NaN,-97.8220,37.7510,...,73,USA,Economics,2022-05-15,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,35,10/5/20 3:41 PM,Completed,149,71.206.51.121,United States,Maryland,Frederick,-77.2758,39.4624,...,68,Vietnam,Finance,2022-12-12,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,36,10/5/20 5:58 PM,Completed,285,129.174.252.234,United States,Virginia,Fairfax,-77.3375,38.8357,...,66,Uzbekistan,Psychology,2021-12-20,OtherAcer/Windows,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

In [ ]:
df5 = df_3
df5['Q3'] = df_2['Q3']

In [ ]:
df5

,Unnamed: 0,Time,Status,Duration (Seconds),IP Address,Country,Region,City / Town / District,Latitude,Longitude,...,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13
0,1,10/3/20 5:49 PM,Completed,11646,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209,...,63,Taiwan,economics,2021-12-31,Apple/MacBook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,NaN
1,2,10/3/20 5:49 PM,Completed,113,98.169.26.134,United States,Virginia,Fairfax,-77.2630,38.8605,...,59,India,Finance,2021-05-01,Apple/MacBook,"Working, but not Full Time",Average user,Average user,Little/none,NaN
2,3,10/3/20 5:49 PM,Completed,572,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645,...,70,India,Computer Applications,2022-06-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,4,10/3/20 5:50 PM,Completed,365,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175,...,66,South Korea,Business Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,NaN
4,5,10/3/20 5:51 PM,Completed,92,138.88.108.230,United States,Virginia,NaN,-97.8220,37.7510,...,70,US,Yes,2021-01-01,2,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,6,10/3/20 5:59 PM,Incomplete,221,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,10/3/20 6:23 PM,Completed,115983,108.48.175.220,United States,Virginia,Arlington,-77.0987,38.8600,...,70,pakistan,Finance,2022-07-15,Microsoft/Windows,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,8,10/3/20 7:10 PM,Incomplete,40,173.67.199.85,United States,Virginia,Ashburn,-77.5390,39.0180,...,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,10/3/20 7:25 PM,Completed,137,74.96.114.12,United States,Virginia,Woodbridge,-77.3197,38.6780,...,71,china,Economic,2021-12-15,Microsoft/Windows,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,NaN
9,10,10/3/20 7:56 PM,Incomplete,179,107.77.241.32,United States,Texas,NaN,-96.8217,32.7787,...,71,Uzbekistan,Economics with Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,10/3/20 8:14 PM,Completed,127,138.88.182.245,United States,Maryland,Takoma Park,-77.0040,38.9827,...,66,USA,BIT,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,12,10/3/20 9:38 PM,Completed,269,72.83.246.60,United States,Virginia,Fairfax,-77.2630,38.8605,...,66,India,Computer Engineering,2021-05-31,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,13,10/3/20 9:41 PM,Completed,117,96.241.43.105,United States,Virginia,Chantilly,-77.4512,38.9036,...,69,Romania,Biology,2021-08-26,Apple/MacBook,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,14,10/3/20 10:49 PM,Completed,5966,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,66,India,Cse,2021-12-25,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,NaN
14,15,10/3/20 11:25 PM,Completed,254,73.134.53.227,United States,Maryland,Hyattsville,-76.8696,38.9544,...,67,China,Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,16,10/4/20 12:28 AM,Completed,526,73.86.219.52,United States,Maryland,Baltimore,-76.6355,39.3555,...,72,Uzbekistan,Economics with Finance,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,17,10/4/20 5:22 AM,Completed,398,69.138.215.127,United States,Virginia,Arlington,-77.1130,38.8747,...,68,USA,Economics,2022-05-31,Microsoft/WindowsApple/MacBook,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,18,10/4/20 5:36 AM,Completed,128253,72.196.231.70,United States,Virginia,Springfield,-77.2333,38.7438,...,60,India,Engineering,2021-01-12,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,19,10/4/20 5:47 AM,Completed,239,100.15.54.17,United States,Virginia,Woodbridge,-77.3197,38.6780,...,67,Ethiopia,Accounting and ISOM,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,20,10/4/20 10:32 AM,Completed,255,184.170.83.239,United States,Virginia,Rustburg,-79.0985,37.2544,...,67,United States,Statistics,2021-12-20,Apple/MacBook,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,21,10/4/20 11:03 AM,Completed,256,100.36.243.102,United States,Virginia,Fairfax,-77.3375,38.8357,...,74,United States,Computer Science,2022-05-01,Microsoft/Windows,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,22,10/4/20 12:34 PM,Completed,674,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,65,India,Computer science,2022-04-16,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,23,10/4/20 1:36 PM,Completed,130,73.163.163.82,United States,Maryland,Baltimore,-76.5570,39.2784,...,67,USA,Mathematics & Statistics,2021-12-18,Microsoft/WindowsApple/MacBook,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,24,10/4/20 1:50 PM,Completed,275,138.88.223.87,United States,Virginia,NaN,-97.8220,37.7510,...,75,Nigeria,Economics,2021-05-14,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,25,10/4/20 9:28 PM,Completed,325,100.36.50.114,United States,Virginia,NaN,-97.8220,37.7510,...,67,USA,Systems Engineering,2022-12-19,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,26,10/5/20 9:37 AM,Completed,257,108.51.59.195,United States,Virginia,Burke,-77.2866,38.7851,...,68,Taiwan,Civil engineering,2021-05-30,0,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,27,10/5/20 9:36 AM,Completed,657,72.83.246.219,United States,Virginia,Fairfax,-77.2630,38.8605,...,72,India,ECE,2021-12-11,Apple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,28,10/5/20 10:36 AM,Completed,1750,100.36.118.186,United States,Virginia,Burke,-77.2866,38.7851,...,61,Nigeria,Quantity Surveying,2023-05-24,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,29,10/5/20 11:02 AM,Completed,887,172.58.187.98,United States,Maryland,Baltimore,-76.6949,39.2820,...,64,India,Bachelor of Engineering,2021-12-30,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,30,10/5/20 11:17 AM,Completed,180,72.196.230.201,United States,Virginia,Springfield,-77.2333,38.7438,...,71,India,B.Tech in CS,2021-12-15,Apple/MacBook,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,31,10/5/20 12:52 PM,Completed,392,108.18.111.204,United States,Virginia,Lorton,-77.2060,38.6911,...,56,United States,BS accounting,2021-05-01,Microsoft/Windows,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,32,10/5/20 12:56 PM,Incomplete,192,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,70,India,Bachelor of engineering,2021-12-21,Microsoft/WindowsApple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,NaN
32,33,10/5/20 1:52 PM,Completed,277,184.191.72.8,United States,Virginia,Falls Church,-77.1425,38.8472,...,70,United States ; Pakistan,Criminology Law and Soci,2021-12-18,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,34,10/5/20 3:34 PM,Completed,119,141.156.160.243,United States,Virginia,NaN,-97.8220,37.7510,...,73,USA,Economics,2022-05-15,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,35,10/5/20 3:41 PM,Completed,149,71.206.51.121,United States,Maryland,Frederick,-77.2758,39.4624,...,68,Vietnam,Finance,2022-12-12,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,36,10/5/20 5:58 PM,Completed,285,129.174.252.234,United States,Virginia,Fairfax,-77.3375,38.8357,...,66,Uzbekistan,Psychology,2021-12-20,OtherAcer/Windows,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

In [ ]:
missing_columns_3 = df5.columns[df5.isna().any()].tolist()

In [ ]:
missing_columns_3

['City / Town / District',
 'Q5',
 'Q6',
 'Q7',
 'Q8',
 'Q9',
 'Q10',
 'Q11',
 'Q12',
 'Q13']

In [ ]:
df5['Q5']

0                        Taiwan
1                         India
2                         India
3                   South Korea
4                            US
5                           NaN
6                      pakistan
7                           NaN
8                         china
9                   Uzbekistan
10                          USA
11                        India
12                      Romania
13                        India
14                        China
15                   Uzbekistan
16                          USA
17                       India
18                     Ethiopia
19                United States
20               United States
21                        India
22                          USA
23                     Nigeria
24                          USA
25                       Taiwan
26                        India
27                      Nigeria
28                        India
29                        India
30                United States
31                        India
32    United States ; Pakistan
33                          USA
34                      Vietnam
35                   Uzbekistan
Name: Q5, dtype: object

In [ ]:
df5['Q5'] = df5['Q5'].str.strip()

In [ ]:
df5['Q5'] = df5['Q5'].str.upper()

In [ ]:
# df_5['Q5'] = df_5['Q5'].fillna('')

In [ ]:
df5['Q5'] = np.where(df5['Q5'] == 'UNITED STATES ; PAKISTAN', 'UNITED STATES', df5['Q5'])
# idx = df5['Q5'].str.contains('UNITED STATES')
# df5.loc[idx,'Q5'] = 'UNITED STATES'

In [ ]:
df5['Q5']

0            TAIWAN
1             INDIA
2             INDIA
3       SOUTH KOREA
4                US
5               NaN
6          PAKISTAN
7               NaN
8             CHINA
9        UZBEKISTAN
10              USA
11            INDIA
12          ROMANIA
13            INDIA
14            CHINA
15       UZBEKISTAN
16              USA
17            INDIA
18         ETHIOPIA
19    UNITED STATES
20    UNITED STATES
21            INDIA
22              USA
23          NIGERIA
24              USA
25           TAIWAN
26            INDIA
27          NIGERIA
28            INDIA
29            INDIA
30    UNITED STATES
31            INDIA
32    UNITED STATES
33              USA
34          VIETNAM
35       UZBEKISTAN
Name: Q5, dtype: object

In [ ]:
modeQ5 = df5["Q5"].mode()
df5["Q5"].fillna(modeQ5.values[0], inplace = True)

Replacing empty values with MODE

In [ ]:
df5['Q5']

0            TAIWAN
1             INDIA
2             INDIA
3       SOUTH KOREA
4                US
5             INDIA
6          PAKISTAN
7             INDIA
8             CHINA
9        UZBEKISTAN
10              USA
11            INDIA
12          ROMANIA
13            INDIA
14            CHINA
15       UZBEKISTAN
16              USA
17            INDIA
18         ETHIOPIA
19    UNITED STATES
20    UNITED STATES
21            INDIA
22              USA
23          NIGERIA
24              USA
25           TAIWAN
26            INDIA
27          NIGERIA
28            INDIA
29            INDIA
30    UNITED STATES
31            INDIA
32    UNITED STATES
33              USA
34          VIETNAM
35       UZBEKISTAN
Name: Q5, dtype: object

In [ ]:
df5

,Unnamed: 0,Time,Status,Duration (Seconds),IP Address,Country,Region,City / Town / District,Latitude,Longitude,...,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13
0,1,10/3/20 5:49 PM,Completed,11646,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209,...,63,TAIWAN,economics,2021-12-31,Apple/MacBook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,NaN
1,2,10/3/20 5:49 PM,Completed,113,98.169.26.134,United States,Virginia,Fairfax,-77.2630,38.8605,...,59,INDIA,Finance,2021-05-01,Apple/MacBook,"Working, but not Full Time",Average user,Average user,Little/none,NaN
2,3,10/3/20 5:49 PM,Completed,572,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645,...,70,INDIA,Computer Applications,2022-06-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,4,10/3/20 5:50 PM,Completed,365,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175,...,66,SOUTH KOREA,Business Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,NaN
4,5,10/3/20 5:51 PM,Completed,92,138.88.108.230,United States,Virginia,NaN,-97.8220,37.7510,...,70,US,Yes,2021-01-01,2,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,6,10/3/20 5:59 PM,Incomplete,221,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,67,INDIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,10/3/20 6:23 PM,Completed,115983,108.48.175.220,United States,Virginia,Arlington,-77.0987,38.8600,...,70,PAKISTAN,Finance,2022-07-15,Microsoft/Windows,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,8,10/3/20 7:10 PM,Incomplete,40,173.67.199.85,United States,Virginia,Ashburn,-77.5390,39.0180,...,62,INDIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,10/3/20 7:25 PM,Completed,137,74.96.114.12,United States,Virginia,Woodbridge,-77.3197,38.6780,...,71,CHINA,Economic,2021-12-15,Microsoft/Windows,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,NaN
9,10,10/3/20 7:56 PM,Incomplete,179,107.77.241.32,United States,Texas,NaN,-96.8217,32.7787,...,71,UZBEKISTAN,Economics with Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,10/3/20 8:14 PM,Completed,127,138.88.182.245,United States,Maryland,Takoma Park,-77.0040,38.9827,...,66,USA,BIT,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,12,10/3/20 9:38 PM,Completed,269,72.83.246.60,United States,Virginia,Fairfax,-77.2630,38.8605,...,66,INDIA,Computer Engineering,2021-05-31,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,13,10/3/20 9:41 PM,Completed,117,96.241.43.105,United States,Virginia,Chantilly,-77.4512,38.9036,...,69,ROMANIA,Biology,2021-08-26,Apple/MacBook,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,14,10/3/20 10:49 PM,Completed,5966,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,66,INDIA,Cse,2021-12-25,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,NaN
14,15,10/3/20 11:25 PM,Completed,254,73.134.53.227,United States,Maryland,Hyattsville,-76.8696,38.9544,...,67,CHINA,Management,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,16,10/4/20 12:28 AM,Completed,526,73.86.219.52,United States,Maryland,Baltimore,-76.6355,39.3555,...,72,UZBEKISTAN,Economics with Finance,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,17,10/4/20 5:22 AM,Completed,398,69.138.215.127,United States,Virginia,Arlington,-77.1130,38.8747,...,68,USA,Economics,2022-05-31,Microsoft/WindowsApple/MacBook,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,18,10/4/20 5:36 AM,Completed,128253,72.196.231.70,United States,Virginia,Springfield,-77.2333,38.7438,...,60,INDIA,Engineering,2021-01-12,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,19,10/4/20 5:47 AM,Completed,239,100.15.54.17,United States,Virginia,Woodbridge,-77.3197,38.6780,...,67,ETHIOPIA,Accounting and ISOM,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,20,10/4/20 10:32 AM,Completed,255,184.170.83.239,United States,Virginia,Rustburg,-79.0985,37.2544,...,67,UNITED STATES,Statistics,2021-12-20,Apple/MacBook,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,21,10/4/20 11:03 AM,Completed,256,100.36.243.102,United States,Virginia,Fairfax,-77.3375,38.8357,...,74,UNITED STATES,Computer Science,2022-05-01,Microsoft/Windows,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,22,10/4/20 12:34 PM,Completed,674,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,65,INDIA,Computer science,2022-04-16,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,23,10/4/20 1:36 PM,Completed,130,73.163.163.82,United States,Maryland,Baltimore,-76.5570,39.2784,...,67,USA,Mathematics & Statistics,2021-12-18,Microsoft/WindowsApple/MacBook,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,24,10/4/20 1:50 PM,Completed,275,138.88.223.87,United States,Virginia,NaN,-97.8220,37.7510,...,75,NIGERIA,Economics,2021-05-14,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,25,10/4/20 9:28 PM,Completed,325,100.36.50.114,United States,Virginia,NaN,-97.8220,37.7510,...,67,USA,Systems Engineering,2022-12-19,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,26,10/5/20 9:37 AM,Completed,257,108.51.59.195,United States,Virginia,Burke,-77.2866,38.7851,...,68,TAIWAN,Civil engineering,2021-05-30,0,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,27,10/5/20 9:36 AM,Completed,657,72.83.246.219,United States,Virginia,Fairfax,-77.2630,38.8605,...,72,INDIA,ECE,2021-12-11,Apple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,28,10/5/20 10:36 AM,Completed,1750,100.36.118.186,United States,Virginia,Burke,-77.2866,38.7851,...,61,NIGERIA,Quantity Surveying,2023-05-24,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,29,10/5/20 11:02 AM,Completed,887,172.58.187.98,United States,Maryland,Baltimore,-76.6949,39.2820,...,64,INDIA,Bachelor of Engineering,2021-12-30,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,30,10/5/20 11:17 AM,Completed,180,72.196.230.201,United States,Virginia,Springfield,-77.2333,38.7438,...,71,INDIA,B.Tech in CS,2021-12-15,Apple/MacBook,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,31,10/5/20 12:52 PM,Completed,392,108.18.111.204,United States,Virginia,Lorton,-77.2060,38.6911,...,56,UNITED STATES,BS accounting,2021-05-01,Microsoft/Windows,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,32,10/5/20 12:56 PM,Incomplete,192,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,70,INDIA,Bachelor of engineering,2021-12-21,Microsoft/WindowsApple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,NaN
32,33,10/5/20 1:52 PM,Completed,277,184.191.72.8,United States,Virginia,Falls Church,-77.1425,38.8472,...,70,UNITED STATES,Criminology Law and Soci,2021-12-18,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,34,10/5/20 3:34 PM,Completed,119,141.156.160.243,United States,Virginia,NaN,-97.8220,37.7510,...,73,USA,Economics,2022-05-15,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,35,10/5/20 3:41 PM,Completed,149,71.206.51.121,United States,Maryland,Frederick,-77.2758,39.4624,...,68,VIETNAM,Finance,2022-12-12,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,36,10/5/20 5:58 PM,Completed,285,129.174.252.234,United States,Virginia,Fairfax,-77.3375,38.8357,...,66,UZBEKISTAN,Psychology,2021-12-20,OtherAcer/Windows,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

In [ ]:
df5["Q6"]

0                    economics
1                     Finance
2        Computer Applications
3          Business Management
4                          Yes
5                          NaN
6                      Finance
7                          NaN
8                     Economic
9      Economics with Finance
10                         BIT
11        Computer Engineering
12                     Biology
13                         Cse
14                  Management
15      Economics with Finance
16                   Economics
17                Engineering
18         Accounting and ISOM
19                  Statistics
20           Computer Science
21           Computer science
22    Mathematics & Statistics
23                   Economics
24         Systems Engineering
25           Civil engineering
26                         ECE
27          Quantity Surveying
28     Bachelor of Engineering
29                B.Tech in CS
30               BS accounting
31     Bachelor of engineering
32    Criminology Law and Soci
33                   Economics
34                     Finance
35                  Psychology
Name: Q6, dtype: object

In [ ]:
df5['Q6'] = df5['Q6'].str.strip()
df5['Q6'] = df5['Q6'].str.upper()
df5['Q6'] = df5['Q6'].replace('YES',np.NaN)

In [ ]:
df5['Q6']

0                    ECONOMICS
1                      FINANCE
2        COMPUTER APPLICATIONS
3          BUSINESS MANAGEMENT
4                          NaN
5                          NaN
6                      FINANCE
7                          NaN
8                     ECONOMIC
9       ECONOMICS WITH FINANCE
10                         BIT
11        COMPUTER ENGINEERING
12                     BIOLOGY
13                         CSE
14                  MANAGEMENT
15      ECONOMICS WITH FINANCE
16                   ECONOMICS
17                 ENGINEERING
18         ACCOUNTING AND ISOM
19                  STATISTICS
20            COMPUTER SCIENCE
21            COMPUTER SCIENCE
22    MATHEMATICS & STATISTICS
23                   ECONOMICS
24         SYSTEMS ENGINEERING
25           CIVIL ENGINEERING
26                         ECE
27          QUANTITY SURVEYING
28     BACHELOR OF ENGINEERING
29                B.TECH IN CS
30               BS ACCOUNTING
31     BACHELOR OF ENGINEERING
32    CRIMINOLOGY LAW AND SOCI
33                   ECONOMICS
34                     FINANCE
35                  PSYCHOLOGY
Name: Q6, dtype: object

In [ ]:
modeQ6 = df5["Q6"].mode()
df5["Q6"].fillna(modeQ6.values[0], inplace = True)

Missing values replaced with Most repeated answer.

In [ ]:
df5['Q6']

0                    ECONOMICS
1                      FINANCE
2        COMPUTER APPLICATIONS
3          BUSINESS MANAGEMENT
4                    ECONOMICS
5                    ECONOMICS
6                      FINANCE
7                    ECONOMICS
8                     ECONOMIC
9       ECONOMICS WITH FINANCE
10                         BIT
11        COMPUTER ENGINEERING
12                     BIOLOGY
13                         CSE
14                  MANAGEMENT
15      ECONOMICS WITH FINANCE
16                   ECONOMICS
17                 ENGINEERING
18         ACCOUNTING AND ISOM
19                  STATISTICS
20            COMPUTER SCIENCE
21            COMPUTER SCIENCE
22    MATHEMATICS & STATISTICS
23                   ECONOMICS
24         SYSTEMS ENGINEERING
25           CIVIL ENGINEERING
26                         ECE
27          QUANTITY SURVEYING
28     BACHELOR OF ENGINEERING
29                B.TECH IN CS
30               BS ACCOUNTING
31     BACHELOR OF ENGINEERING
32    CRIMINOLOGY LAW AND SOCI
33                   ECONOMICS
34                     FINANCE
35                  PSYCHOLOGY
Name: Q6, dtype: object

In [ ]:
missing_columns_4 = df5.columns[df5.isna().any()].tolist()
missing_columns_4

['City / Town / District', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11', 'Q12', 'Q13']

Q7, missing values replaced with mode since it is most likely that the student with the missing value was also from the batch that had most students

In [ ]:
modeQ7 = df5["Q7"].mode()
df5["Q7"].fillna(modeQ7.values[0], inplace = True)
df5['Q7']

0     2021-12-31
1     2021-05-01
2     2022-06-01
3     2021-12-31
4     2021-01-01
5     2021-12-20
6     2022-07-15
7     2021-12-20
8     2021-12-15
9     2021-12-20
10    2022-05-01
11    2021-05-31
12    2021-08-26
13    2021-12-25
14    2021-12-31
15    2022-05-01
16    2022-05-31
17    2021-01-12
18    2021-12-20
19    2021-12-20
20    2022-05-01
21    2022-04-16
22    2021-12-18
23    2021-05-14
24    2022-12-19
25    2021-05-30
26    2021-12-11
27    2023-05-24
28    2021-12-30
29    2021-12-15
30    2021-05-01
31    2021-12-21
32    2021-12-18
33    2022-05-15
34    2022-12-12
35    2021-12-20
Name: Q7, dtype: object

In [ ]:
df5['Q8']

0                      Apple/MacBook
1                      Apple/MacBook
2                      Apple/MacBook
3                  Microsoft/Windows
4                                  2
5                                NaN
6                  Microsoft/Windows
7                                NaN
8                  Microsoft/Windows
9                                NaN
10                 Microsoft/Windows
11                 Microsoft/Windows
12                     Apple/MacBook
13                 Microsoft/Windows
14                 Microsoft/Windows
15                 Microsoft/Windows
16    Microsoft/WindowsApple/MacBook
17                 Microsoft/Windows
18                 Microsoft/Windows
19                     Apple/MacBook
20                 Microsoft/Windows
21                 Microsoft/Windows
22    Microsoft/WindowsApple/MacBook
23                 Microsoft/Windows
24                 Microsoft/Windows
25                                 0
26                     Apple/MacBook
27                 Microsoft/Windows
28                 Microsoft/Windows
29                     Apple/MacBook
30                 Microsoft/Windows
31    Microsoft/WindowsApple/MacBook
32                 Microsoft/Windows
33                 Microsoft/Windows
34                 Microsoft/Windows
35                 OtherAcer/Windows
Name: Q8, dtype: object

In [ ]:
df5['Q8'] = np.where(df5['Q8'] == '2', 'Apple/MacBook', df5['Q8'])
df5['Q8'] = np.where(df5['Q8'] == 'OtherAcer/Windows', 'Microsoft/Windows', df5['Q8'])
df5['Q8'] = np.where(df5['Q8'] == '0', 'Microsoft/Windows', df5['Q8'])
df5['Q8'] = np.where(df5['Q8'] == 'Microsoft/WindowsApple/MacBook', 'Microsoft/Windows', df5['Q8'])

In [ ]:
df5['Q8']

0         Apple/MacBook
1         Apple/MacBook
2         Apple/MacBook
3     Microsoft/Windows
4         Apple/MacBook
5                   NaN
6     Microsoft/Windows
7                   NaN
8     Microsoft/Windows
9                   NaN
10    Microsoft/Windows
11    Microsoft/Windows
12        Apple/MacBook
13    Microsoft/Windows
14    Microsoft/Windows
15    Microsoft/Windows
16    Microsoft/Windows
17    Microsoft/Windows
18    Microsoft/Windows
19        Apple/MacBook
20    Microsoft/Windows
21    Microsoft/Windows
22    Microsoft/Windows
23    Microsoft/Windows
24    Microsoft/Windows
25    Microsoft/Windows
26        Apple/MacBook
27    Microsoft/Windows
28    Microsoft/Windows
29        Apple/MacBook
30    Microsoft/Windows
31    Microsoft/Windows
32    Microsoft/Windows
33    Microsoft/Windows
34    Microsoft/Windows
35    Microsoft/Windows
Name: Q8, dtype: object

In [ ]:
modeQ8 = df5["Q8"].mode()
df5["Q8"].fillna(modeQ8.values[0], inplace = True)
df5['Q8']

0         Apple/MacBook
1         Apple/MacBook
2         Apple/MacBook
3     Microsoft/Windows
4         Apple/MacBook
5     Microsoft/Windows
6     Microsoft/Windows
7     Microsoft/Windows
8     Microsoft/Windows
9     Microsoft/Windows
10    Microsoft/Windows
11    Microsoft/Windows
12        Apple/MacBook
13    Microsoft/Windows
14    Microsoft/Windows
15    Microsoft/Windows
16    Microsoft/Windows
17    Microsoft/Windows
18    Microsoft/Windows
19        Apple/MacBook
20    Microsoft/Windows
21    Microsoft/Windows
22    Microsoft/Windows
23    Microsoft/Windows
24    Microsoft/Windows
25    Microsoft/Windows
26        Apple/MacBook
27    Microsoft/Windows
28    Microsoft/Windows
29        Apple/MacBook
30    Microsoft/Windows
31    Microsoft/Windows
32    Microsoft/Windows
33    Microsoft/Windows
34    Microsoft/Windows
35    Microsoft/Windows
Name: Q8, dtype: object

Replacing null entries with MODE

In [ ]:
modeQ9 = df5["Q9"].mode()
df5["Q9"].fillna(modeQ9.values[0], inplace = True)
df5['Q9']

0     Not Working while attending Mason
1            Working, but not Full Time
2                        Yes, Full Time
3     Not Working while attending Mason
4                        Yes, Full Time
5     Not Working while attending Mason
6            Working, but not Full Time
7     Not Working while attending Mason
8                        Yes, Full Time
9     Not Working while attending Mason
10    Not Working while attending Mason
11    Not Working while attending Mason
12           Working, but not Full Time
13    Not Working while attending Mason
14    Not Working while attending Mason
15    Not Working while attending Mason
16                       Yes, Full Time
17    Not Working while attending Mason
18    Not Working while attending Mason
19           Working, but not Full Time
20                       Yes, Full Time
21    Not Working while attending Mason
22           Working, but not Full Time
23    Not Working while attending Mason
24                       Yes, Full Time
25                       Yes, Full Time
26    Not Working while attending Mason
27    Not Working while attending Mason
28    Not Working while attending Mason
29    Not Working while attending Mason
30                       Yes, Full Time
31    Not Working while attending Mason
32                       Yes, Full Time
33                       Yes, Full Time
34    Not Working while attending Mason
35                       Yes, Full Time
Name: Q9, dtype: object

Replacing null entries with MODE

In [ ]:
modeQ10 = df5["Q10"].mode()
df5["Q10"].fillna(modeQ10.values[0], inplace = True)
df5['Q10']

0              Some familiarity
1                  Average user
2              Some familiarity
3                  Average user
4              Some familiarity
5                  Average user
6                  Average user
7                  Average user
8              Some familiarity
9                  Average user
10                  Little/none
11    Frequent use for projects
12             Some familiarity
13                 Average user
14                 Average user
15             Some familiarity
16                 Average user
17    Frequent use for projects
18                  Little/none
19             Some familiarity
20             Some familiarity
21             Some familiarity
22             Some familiarity
23                  Little/none
24                 Average user
25                 Average user
26                 Average user
27                 Average user
28                 Average user
29                 Average user
30                  Little/none
31                 Average user
32                 Average user
33                 Average user
34             Some familiarity
35             Some familiarity
Name: Q10, dtype: object

Replace Null entries with MODE

In [ ]:
modeQ11 = df5["Q11"].mode()
df5["Q11"].fillna(modeQ11.values[0], inplace = True)
df5['Q11']

0                   Little/none
1                  Average user
2                   Little/none
3     Frequent use for projects
4              Some familiarity
5                  Average user
6                  Average user
7                  Average user
8     Frequent use for projects
9                  Average user
10                  Little/none
11                 Average user
12                 Average user
13                 Average user
14                  Little/none
15             Some familiarity
16             Some familiarity
17    Frequent use for projects
18                  Little/none
19                Fluent/expert
20             Some familiarity
21                  Little/none
22    Frequent use for projects
23                  Little/none
24                 Average user
25             Some familiarity
26    Frequent use for projects
27    Frequent use for projects
28                 Average user
29                 Average user
30             Some familiarity
31    Frequent use for projects
32             Some familiarity
33                 Average user
34             Some familiarity
35                  Little/none
Name: Q11, dtype: object

In [ ]:
df5["Q12"]

0              Some familiarity
1                   Little/none
2                  Average user
3              Some familiarity
4                  Average user
5                           NaN
6                  Average user
7                           NaN
8                  Average user
9                           NaN
10             Some familiarity
11    Frequent use for projects
12                 Average user
13                 Average user
14                  Little/none
15             Some familiarity
16             Some familiarity
17                 Average user
18                 Average user
19                 Average user
20             Some familiarity
21                 Average user
22                  Little/none
23                  Little/none
24                 Average user
25             Some familiarity
26                 Average user
27                 Average user
28                 Average user
29    Frequent use for projects
30             Some familiarity
31    Frequent use for projects
32             Some familiarity
33                 Average user
34             Some familiarity
35                  Little/none
Name: Q12, dtype: object

Replaced null entries with MODE

In [ ]:
modeQ12 = df5["Q12"].mode()
df5["Q12"].fillna(modeQ12.values[0], inplace = True)
df5['Q12']

0              Some familiarity
1                   Little/none
2                  Average user
3              Some familiarity
4                  Average user
5                  Average user
6                  Average user
7                  Average user
8                  Average user
9                  Average user
10             Some familiarity
11    Frequent use for projects
12                 Average user
13                 Average user
14                  Little/none
15             Some familiarity
16             Some familiarity
17                 Average user
18                 Average user
19                 Average user
20             Some familiarity
21                 Average user
22                  Little/none
23                  Little/none
24                 Average user
25             Some familiarity
26                 Average user
27                 Average user
28                 Average user
29    Frequent use for projects
30             Some familiarity
31    Frequent use for projects
32             Some familiarity
33                 Average user
34             Some familiarity
35                  Little/none
Name: Q12, dtype: object

In [ ]:
df5['Q13']

0                                                   NaN
1                                                   NaN
2     As part of my work, I have access to a lot of ...
3                                                   NaN
4                                                 Learn
5                                                   NaN
6     To deduce meaningful interpretation for Financ...
7                                                   NaN
8                                                   NaN
9                                                   NaN
10    To see if it is a field I am interested in pur...
11    To learn and explore cutting edge data technol...
12    Learn to select the appropriate tools to condu...
13                                                  NaN
14                                    improve my skills
15    My professional goal is to become a Financial ...
16    able to compliment my Computational Social Sci...
17                                  To start a company
18    To be able understand and manipulate data to m...
19    My ultimate goal is to get a job as a sports a...
20    To understand how to properly interpret and di...
21    After graduating data analytics, I want myself...
22    Learning how to appropriately handle large qua...
23    To learn and understand the fundamentals and m...
24    The goal is to learn as many programming/stati...
25       Learning analytics tool and being good at them
26                      I want to be as a data analyst
27    It is very relevant to my PhD research area an...
28    Learn how to handle large amount structured an...
29    To become a good Data Analyst and work for top...
30    Get a better understanding of the granularity ...
31                                                  NaN
32                       Learn how data analytics works
33                    Advance my career in data science
34                                   Getting a good job
35                           to use the skills at work.
Name: Q13, dtype: object

Since this is a subjective question and not with a limited response, filling in missing values using methods such as mean, mode is not a good option.

In [ ]:
df5["Q13"].fillna('', inplace = True)

In [ ]:
df5['Q13']

0
1
2     As part of my work, I have access to a lot of ...
3
4                                                 Learn
5
6     To deduce meaningful interpretation for Financ...
7
8
9
10    To see if it is a field I am interested in pur...
11    To learn and explore cutting edge data technol...
12    Learn to select the appropriate tools to condu...
13
14                                    improve my skills
15    My professional goal is to become a Financial ...
16    able to compliment my Computational Social Sci...
17                                  To start a company
18    To be able understand and manipulate data to m...
19    My ultimate goal is to get a job as a sports a...
20    To understand how to properly interpret and di...
21    After graduating data analytics, I want myself...
22    Learning how to appropriately handle large qua...
23    To learn and understand the fundamentals and m...
24    The goal is to learn as many programming/stati...
25       Learning analytics tool and being good at them
26                      I want to be as a data analyst
27    It is very relevant to my PhD research area an...
28    Learn how to handle large amount structured an...
29    To become a good Data Analyst and work for top...
30    Get a better understanding of the granularity ...
31
32                       Learn how data analytics works
33                    Advance my career in data science
34                                   Getting a good job
35                           to use the skills at work.
Name: Q13, dtype: object

In [ ]:
df5

,Unnamed: 0,Time,Status,Duration (Seconds),IP Address,Country,Region,City / Town / District,Latitude,Longitude,...,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13
0,1,10/3/20 5:49 PM,Completed,11646,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209,...,63,TAIWAN,ECONOMICS,2021-12-31,Apple/MacBook,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,
1,2,10/3/20 5:49 PM,Completed,113,98.169.26.134,United States,Virginia,Fairfax,-77.2630,38.8605,...,59,INDIA,FINANCE,2021-05-01,Apple/MacBook,"Working, but not Full Time",Average user,Average user,Little/none,
2,3,10/3/20 5:49 PM,Completed,572,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645,...,70,INDIA,COMPUTER APPLICATIONS,2022-06-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,4,10/3/20 5:50 PM,Completed,365,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175,...,66,SOUTH KOREA,BUSINESS MANAGEMENT,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,
4,5,10/3/20 5:51 PM,Completed,92,138.88.108.230,United States,Virginia,NaN,-97.8220,37.7510,...,70,US,ECONOMICS,2021-01-01,Apple/MacBook,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,6,10/3/20 5:59 PM,Incomplete,221,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,67,INDIA,ECONOMICS,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,
6,7,10/3/20 6:23 PM,Completed,115983,108.48.175.220,United States,Virginia,Arlington,-77.0987,38.8600,...,70,PAKISTAN,FINANCE,2022-07-15,Microsoft/Windows,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,8,10/3/20 7:10 PM,Incomplete,40,173.67.199.85,United States,Virginia,Ashburn,-77.5390,39.0180,...,62,INDIA,ECONOMICS,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,
8,9,10/3/20 7:25 PM,Completed,137,74.96.114.12,United States,Virginia,Woodbridge,-77.3197,38.6780,...,71,CHINA,ECONOMIC,2021-12-15,Microsoft/Windows,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,
9,10,10/3/20 7:56 PM,Incomplete,179,107.77.241.32,United States,Texas,NaN,-96.8217,32.7787,...,71,UZBEKISTAN,ECONOMICS WITH FINANCE,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,
10,11,10/3/20 8:14 PM,Completed,127,138.88.182.245,United States,Maryland,Takoma Park,-77.0040,38.9827,...,66,USA,BIT,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,12,10/3/20 9:38 PM,Completed,269,72.83.246.60,United States,Virginia,Fairfax,-77.2630,38.8605,...,66,INDIA,COMPUTER ENGINEERING,2021-05-31,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,13,10/3/20 9:41 PM,Completed,117,96.241.43.105,United States,Virginia,Chantilly,-77.4512,38.9036,...,69,ROMANIA,BIOLOGY,2021-08-26,Apple/MacBook,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,14,10/3/20 10:49 PM,Completed,5966,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,66,INDIA,CSE,2021-12-25,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,
14,15,10/3/20 11:25 PM,Completed,254,73.134.53.227,United States,Maryland,Hyattsville,-76.8696,38.9544,...,67,CHINA,MANAGEMENT,2021-12-31,Microsoft/Windows,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,16,10/4/20 12:28 AM,Completed,526,73.86.219.52,United States,Maryland,Baltimore,-76.6355,39.3555,...,72,UZBEKISTAN,ECONOMICS WITH FINANCE,2022-05-01,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,17,10/4/20 5:22 AM,Completed,398,69.138.215.127,United States,Virginia,Arlington,-77.1130,38.8747,...,68,USA,ECONOMICS,2022-05-31,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,18,10/4/20 5:36 AM,Completed,128253,72.196.231.70,United States,Virginia,Springfield,-77.2333,38.7438,...,60,INDIA,ENGINEERING,2021-01-12,Microsoft/Windows,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,19,10/4/20 5:47 AM,Completed,239,100.15.54.17,United States,Virginia,Woodbridge,-77.3197,38.6780,...,67,ETHIOPIA,ACCOUNTING AND ISOM,2021-12-20,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,20,10/4/20 10:32 AM,Completed,255,184.170.83.239,United States,Virginia,Rustburg,-79.0985,37.2544,...,67,UNITED STATES,STATISTICS,2021-12-20,Apple/MacBook,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,21,10/4/20 11:03 AM,Completed,256,100.36.243.102,United States,Virginia,Fairfax,-77.3375,38.8357,...,74,UNITED STATES,COMPUTER SCIENCE,2022-05-01,Microsoft/Windows,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,22,10/4/20 12:34 PM,Completed,674,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,...,65,INDIA,COMPUTER SCIENCE,2022-04-16,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,23,10/4/20 1:36 PM,Completed,130,73.163.163.82,United States,Maryland,Baltimore,-76.5570,39.2784,...,67,USA,MATHEMATICS & STATISTICS,2021-12-18,Microsoft/Windows,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,24,10/4/20 1:50 PM,Completed,275,138.88.223.87,United States,Virginia,NaN,-97.8220,37.7510,...,75,NIGERIA,ECONOMICS,2021-05-14,Microsoft/Windows,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,25,10/4/20 9:28 PM,Completed,325,100.36.50.114,United States,Virginia,NaN,-97.8220,37.7510,...,67,USA,SYSTEMS ENGINEERING,2022-12-19,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,26,10/5/20 9:37 AM,Completed,257,108.51.59.195,United States,Virginia,Burke,-77.2866,38.7851,...,68,TAIWAN,CIVIL ENGINEERING,2021-05-30,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,27,10/5/20 9:36 AM,Completed,657,72.83.246.219,United States,Virginia,Fairfax,-77.2630,38.8605,...,72,INDIA,ECE,2021-12-11,Apple/MacBook,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,28,10/5/20 10:36 AM,Completed,1750,100.36.118.186,United States,Virginia,Burke,-77.2866,38.7851,...,61,NIGERIA,QUANTITY SURVEYING,2023-05-24,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,29,10/5/20 11:02 AM,Completed,887,172.58.187.98,United States,Maryland,Baltimore,-76.6949,39.2820,...,64,INDIA,BACHELOR OF ENGINEERING,2021-12-30,Microsoft/Windows,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,30,10/5/20 11:17 AM,Completed,180,72.196.230.201,United States,Virginia,Springfield,-77.2333,38.7438,...,71,INDIA,B.TECH IN CS,2021-12-15,Apple/MacBook,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,31,10/5/20 12:52 PM,Completed,392,108.18.111.204,United States,Virginia,Lorton,-77.2060,38.6911,...,56,UNITED STATES,BS ACCOUNTING,2021-05-01,Microsoft/Windows,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,32,10/5/20 12:56 PM,Incomplete,192,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,...,70,INDIA,BACHELOR OF ENGINEERING,2021-12-21,Microsoft/Windows,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,
32,33,10/5/20 1:52 PM,Completed,277,184.191.72.8,United States,Virginia,Falls Church,-77.1425,38.8472,...,70,UNITED STATES,CRIMINOLOGY LAW AND SOCI,2021-12-18,Microsoft/Windows,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,34,10/5/20 3:34 PM,Completed,119,141.156.160.243,United States,Virginia,NaN,-97.8220,37.7510,...,73,USA,ECONOMICS,2022-05-15,Microsoft/Windows,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,35,10/5/20 3:41 PM,Completed,149,71.206.51.121,United States,Maryland,Frederick,-77.2758,39.4624,...,68,VIETNAM,FINANCE,2022-12-12,Microsoft/Windows,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,36,10/5/20 5:58 PM,Completed,285,129.174.252.234,United States,Virginia,Fairfax,-77.3375,38.8357,...,66,UZBEKISTAN,PSYCHOLOGY,2021-12-20,Microsoft/Windows,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

In [ ]:
missing_columns_5 = df5.columns[df5.isna().any()].tolist()
missing_columns_5

['City / Town / District']

Replacing missing values with MODE

In [ ]:
modeCity = df5['City / Town / District'].mode()
df5['City / Town / District'].fillna(modeCity.values[0], inplace = True)
df5['City / Town / District']

0            Fairfax
1            Fairfax
2     Greenway Downs
3        Gainesville
4            Fairfax
5             Reston
6          Arlington
7            Ashburn
8         Woodbridge
9            Fairfax
10       Takoma Park
11           Fairfax
12         Chantilly
13             Burke
14       Hyattsville
15         Baltimore
16         Arlington
17       Springfield
18        Woodbridge
19          Rustburg
20           Fairfax
21            Reston
22         Baltimore
23           Fairfax
24           Fairfax
25             Burke
26           Fairfax
27             Burke
28         Baltimore
29       Springfield
30            Lorton
31             Burke
32      Falls Church
33           Fairfax
34         Frederick
35           Fairfax
Name: City / Town / District, dtype: object

In [ ]:
df5.to_csv("CleanedCSV.csv")

# Part 3
Statistical Summaries

In [ ]:
descriptionLst = []
qNum = 1
while qNum != 14:
  col = 'Q' + str(qNum)
  temp = df5[col].describe()
  descriptionLst.append(temp)
  qNum += 1

Since the mean is near to the value 2.0, most of the students who attempted the survey belonged to the section 002

In [ ]:
descriptionLst[0]

count    36.000000
mean      2.888889
std       1.007905
min       2.000000
25%       2.000000
50%       2.000000
75%       4.000000
max       4.000000
Name: Q1, dtype: float64

Majority of the gender types were Male with 18 occurrences

In [ ]:
descriptionLst[1]

count       36
unique       4
top       Male
freq        18
Name: Q2, dtype: object

On average, the age of every student answering the survey was around 27. However, it can be seen that there is a quite a broad range of students enrolled with the max going up till 55 and a min of 22.

In [ ]:
descriptionLst[2]

count    36.000000
mean     27.111111
std       6.492975
min      22.000000
25%      23.000000
50%      25.000000
75%      28.000000
max      55.000000
Name: Q3, dtype: float64

On average, the height of every student was around 67 inches. There is a good standard deviation involved implying that there is a good spread in heights of students. This could also be the case because some students don't truly know their exact heights. Causing a false spread in the result.

In [ ]:
descriptionLst[3]

count    36.000000
mean     67.333333
std       4.222389
min      56.000000
25%      66.000000
50%      67.000000
75%      70.000000
max      75.000000
Name: Q4, dtype: float64

Majority of the students were from India. However, since out of 36 students, 13 were from unique countries, it can be said that there is a good diversity of students in terms of ethinic background.

In [ ]:
descriptionLst[4]

count        36
unique       13
top       INDIA
freq         12
Name: Q5, dtype: object

While this data can be a bit faulty in terms of cleaning, but what seems is that Economics is the most popular degree that students were enrolled in. However, since there are 25 unique values, this analysis seems to be incorrect. For example BSc Economics and Economics are considered as two separate entries leading to poor analysis.

In [ ]:
descriptionLst[5]

count            36
unique           25
top       ECONOMICS
freq              7
Name: Q6, dtype: object

Again, similar to the previous analysis, what seems is that most of the students are expected to graduate by 2021-12-20 but with 24 unique values, this doesn't imply a very sound analysis. Or, it could also mean that not many students from a common batch answered the survey.

In [ ]:
descriptionLst[6]

count             36
unique            24
top       2021-12-20
freq               6
Name: Q7, dtype: object

Taking the lead here, majoirty of the students use a windows laptop.

In [ ]:
descriptionLst[7]

count                    36
unique                    2
top       Microsoft/Windows
freq                     28
Name: Q8, dtype: object

A good majority of the students don't work while they are enrolled at Mason

In [ ]:
descriptionLst[8]

count                                    36
unique                                    3
top       Not Working while attending Mason
freq                                     20
Name: Q9, dtype: object

Around half of the students consider themselves as an average coder in Python. This could be a good analysis for the course makers at Mason. They could introduce more Python-based courses.

In [ ]:
descriptionLst[9]

count               36
unique               4
top       Average user
freq                18
Name: Q10, dtype: object

While still taking a majority, but less than being exact half of the population, many students consider themselves as an average coder in R.

In [ ]:
descriptionLst[10]

count               36
unique               5
top       Average user
freq                12
Name: Q11, dtype: object

A very similar description to that of Q10.

In [ ]:
descriptionLst[11]

count               36
unique               4
top       Average user
freq                18
Name: Q12, dtype: object

Since this was a purely subjective question, there is no leading or most frequent common goal. While it may be a common goal but with different way of entering the answer. Hence, this particular analysis is not a good one indeed.

In [ ]:
descriptionLst[12]

count     36
unique    28
top
freq       9
Name: Q13, dtype: object